name: CI

on:
  push:
    branch: [dev, main]

jobs:
  dev-push:
    runs-on: ubuntu-latest
    if: ${BRANCH_NAME} == 'dev'
    steps:
    - uses: actions/checkout@v1
    - name: Push to registry
      uses: elgohr/Publish-Docker-Github-Action@2.6
      with:
          name: dev-de/airflow:ci-${{ github.sha }}
          username: _
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          registry: registry.demo-astro.astronomer-trials.com
  prod-push:
    runs-on: ubuntu-latest
    if: ${BRANCH_NAME} == 'main'
    steps:
    - uses: actions/checkout@v1
    - name: Push to registry
      uses: elgohr/Publish-Docker-Github-Action@2.6
      with:
          name: prod-de/airflow:ci-${{ github.sha }}
          username: _
          password: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          registry: registry.demo-astro.astronomer-trials.com
